/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/arrow.glb --types --keepnames --output components/webgl/Arrow.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { ThreeElements } from '@react-three/fiber'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    g_groupNumber_0_n3d: THREE.Mesh
  }
  materials: {
    matte_material11: THREE.MeshStandardMaterial
  }
}

export function Arrow(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/models/arrow.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="g_groupNumber_0_n3d" geometry={nodes.g_groupNumber_0_n3d.geometry} material={materials.matte_material11} position={[-5.549, 2.201, -2.095]} scale={1.534} />
    </group>
  )
}

useGLTF.preload('/models/arrow.glb')
