/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/contact.glb --types --keepnames --output components/webgl/Contact.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    g_groupNumber_0_n3d: THREE.Mesh
  }
  materials: {
    water_material7: THREE.MeshStandardMaterial
  }
}

export function Contact(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/contact.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="g_groupNumber_0_n3d" geometry={nodes.g_groupNumber_0_n3d.geometry} material={materials.water_material7} position={[0.157, 1.782, 0.18]} scale={2.199} />
    </group>
  )
}

useGLTF.preload('/models/contact.glb')
