/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/hello.glb --types --keepnames --output components/webgl/Hello.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    g_groupNumber_0_n3d: THREE.Mesh
  }
  materials: {
    water_material3: THREE.MeshStandardMaterial
  }
}

export function Hello(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/hello.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="g_groupNumber_0_n3d" geometry={nodes.g_groupNumber_0_n3d.geometry} material={materials.water_material3} position={[8.158, 2.861, -62.453]} scale={8.019} />
    </group>
  )
}

useGLTF.preload('/models/hello.glb')
